

### Register device
POST {{baseUrl}}/api/v1/devices
Content-Type: application/json

{
  "id": "{{deviceId_1}}",
  "type": "HEATING_SYSTEM",
  "model": "Mi Smart Space Heater (1)",
  "serialNumber": "00-B0-D0-63-C4-21",
  "hardwareVersion": "BHR4037GL"
}


### Get Device Info 1
GET {{baseUrl}}/api/v1/devices/{{deviceId_1}}

### Get Device Info 1
GET {{baseUrl}}/api/v1/devices/{{deviceId_2}}


### Get Sensor Telemetry
GET {{baseUrl}}/api/v1/devices/{{deviceId_1}}/state

### Send Sensor Telemetry
PATCH {{baseUrl}}/api/v1/devices/{{deviceId_1}}/state
Content-Type: application/json

{
  "isOn": true,
  "targetTemperature": 22
}
