spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/smart_home
    username: ${DB_USER:postgres}
    password: ${DB_PASS:}
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql

mqtt:
  url: ${MQTT_CONNECTION_URL:tcp://localhost:1883}
  topic: devices/+/+

services:
  sh-device-core:
    url: ${SERVICE_DEVICE_CORE_URL:http://sh-device-core:8080}
  sh-users:
    url: ${SERVICE_USERS_URL:http://sh-users:8080}
  sh-telemetry:
    url: ${SERVICE_TELEMETRY_URL:http://sh-telemetry:8080}

server:
  port: 8080
