{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: {{ $service.serviceType | default $.Values.service.type }}
  ports:
    - port: {{ $service.servicePort }}
      targetPort: {{ $service.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ $name }}
  {{- end }}
