replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

ingress:
  enabled: false
#  annotations:
#    kubernetes.io/ingress.class: nginx

#  hosts:
#    - host: sh-users.local
#      paths: ["/"]
#    - host: sh-device-core.local
#      paths: ["/"]
#    - host: sh-telemetry.local
#      paths: ["/"]
#    - host: sh-monolith.local
#      paths: [ "/" ]

services:
  mosquitto:
    image: eclipse-mosquitto
    containerPort: 1883
    servicePort: 1883
    args:
      - "/bin/sh"
      - "-c"
      - |
        echo 'allow_anonymous true' > /mosquitto/config/mosquitto.conf &&
        echo 'bind_address 0.0.0.0' >> /mosquitto/config/mosquitto.conf &&
        echo 'log_type all' >> /mosquitto/config/mosquitto.conf &&
        mosquitto -c /mosquitto/config/mosquitto.conf
    env: []

  mongo:
    image: mongo
    containerPort: 27017
    servicePort: 27017

  clickhouse:
    image: yandex/clickhouse-server:latest
    containerPort: 8123
    servicePort: 8123
    env:
      - name: CLICKHOUSE_USER
        value: default
      - name: CLICKHOUSE_DB
        value: default

  postgres:
    image: postgres
    containerPort: 5432
    servicePort: 5432
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
      - name: POSTGRES_DB
        value: smart_home

  sh-monolith:
    image: sh-monolith
    containerPort: 8080
    servicePort: 8080
    env:
      - name: DB_HOST
        value: postgres
      - name: DB_PASS
        value: postgres
      - name: SERVICE_DEVICE_CORE_URL
        value: http://sh-device-core:8080
      - name: MQTT_CONNECTION_URL
        value: tcp://mosquitto:1883

  sh-users:
    image: sh-users
    containerPort: 8080
    servicePort: 8080
    env:
      - name: DB_CONNECTION_URL
        value: mongodb://mongo:27017/sh_users

  sh-device-core:
    image: sh-device-core
    containerPort: 8080
    servicePort: 8080
    env:
      - name: DB_CONNECTION_URL
        value: mongodb://mongo:27017/sh_telemetry
      - name: MQTT_CONNECTION_URL
        value: tcp://mosquitto:1883

  sh-telemetry:
    image: sh-telemetry
    containerPort: 8080
    servicePort: 8080
    env:
      - name: DB_CONNECTION_URL
        value: jdbc:clickhouse://clickhouse:8123/default
      - name: MQTT_CONNECTION_URL
        value: tcp://mosquitto:1883
