name: ci

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run tests in sh-device-core
        working-directory: services/sh-device-core
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push smart-home-monolith
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: smart-home-monolith
          push: true
          tags: ghcr.io/sapl/smart-home-monolith:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push sh-device-core
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: services/sh-device-core
          push: true
          tags: ghcr.io/sapl/sh-device-core:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Build and push sh-telemetry
#        uses: docker/build-push-action@v6
#        with:
#          platforms: linux/amd64,linux/arm64
#          context: services/sh-telemetry
#          push: true
#          tags: ghcr.io/sapl/sh-telemetry:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Helm upgrade deployment
        run: helm upgrade smart-home-services ./k8s/helm